services:
  - type: worker
    name: telegram-quizbot
    env: python
    buildCommand: pip install --no-cache-dir -r requirements.txt
    startCommand: python quizbot_clone.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
