services:
  - type: worker
    name: telegram-quizbot
    env: python
    pythonVersion: 3.11.9
    buildCommand: pip install --no-cache-dir -r requirements.txt
    startCommand: python quizbot_clone.py
